card/urls.py
# -*- coding: utf-8 -*-
"""wedding URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url
import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^chat/$', views.chat, name='chat'),
    url(r'^chat/bot/$', views.chat_bot, name='chat_bot'),
    url(r'^chat/send/$', views.chat_send, name='chat_send'),
    url(r'^board/$', views.board, name='board'),
    url(r'^article/$', views.article, name='article'),
    url(r'^album/$', views.album, name='album'),
    url(r'^chatroom/$', views.chatroom, name='chatroom'),
]

wedding/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from card import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^card/', include('card.urls', namespace='card')),
    url(r'^event/', views.event),
    url(r'^$', RedirectView.as_view(url='card/', permanent=False))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

card/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils import timezone
from django.utils.timezone import localtime


# Create your models here.
class User(models.Model):
    name = models.CharField(max_length=50, default='', verbose_name=u'이름')
    last_number = models.CharField(max_length=4, blank=True, default='', verbose_name=u'전화번호 뒷 4자리')
    is_staff = models.BooleanField(default=False, verbose_name=u'관리자 여부')
    profile = models.CharField(max_length=255, default='', blank=True, verbose_name=u'프로필 사진 경로')

    is_invited = models.BooleanField(default=False, verbose_name=u'초대된 여부')

    date_joined_at = models.DateTimeField(default=timezone.now, verbose_name=u'최초 접속일')
    last_login_at = models.DateTimeField(default=timezone.now, verbose_name=u'최근 접속일')

    def __unicode__(self):
        return u"%s%s" % (self.name, self.last_number)

    class Meta:
        verbose_name_plural = u'사용자 목록'
        verbose_name = u'사용자'


class ChatRooms(models.Model):

    title = models.CharField(max_length=255, verbose_name=u'채팅방 이름')
    owner = models.ForeignKey(User, verbose_name=u'채팅방 소유자')

    members = models.TextField(default='', verbose_name=u'구성원')
    # last_log = models.ForeignKey(ChatLogs, verbose_name=u'최근 메세지 아이디')
    # last_message = models.TextField(default='', verbose_name=u'최근 메세지')
    last_updated_at = models.DateTimeField(null=True, verbose_name=u'최근 업데이트 시간')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=u'생성시간')

    @property
    def members_names(self):
        member_ids = self.members.split(',')

        members = []
        for member_id in member_ids:
            members.append(User.objects.get(id=member_id))

        return [unicode(m.name) for m in members]

    def __unicode__(self):
        return u"[%s] %s" % (self.id, self.title)

    class Meta:
        verbose_name_plural = u'채팅방 목록'
        verbose_name = u'채팅방'


class ChatLogs(models.Model):
    MESSAGE_TYPES = (
        ('me', u'자신'),
        ('other', u'상대방'),
        ('notice', u'공지')
    )

    chatroom = models.ForeignKey(ChatRooms, db_index=True, verbose_name=u'채팅방',
                                 on_delete=models.CASCADE)
    type = models.CharField(max_length=15, default='me', choices=MESSAGE_TYPES, verbose_name=u'메세지 종류')
    # 누가 쓴 메세지인지
    user = models.ForeignKey(User, verbose_name=u'사용자')
    message = models.TextField(default='', verbose_name=u'메세지')

    unread_count = models.PositiveSmallIntegerField(default=0, verbose_name=u'읽음 표시')

    created_at = models.DateTimeField(auto_now_add=True, verbose_name=u'작성시간')

    def save(self, *args, **kwargs):
        super(ChatLogs, self).save(*args, **kwargs)

        self.chatroom.last_updated_at = self.created_at
        self.chatroom.save()

    def __unicode__(self):
        return u"[%s] - %s" % (self.id, self.chatroom)

    class Meta:
        verbose_name_plural = u'채팅 목록'
        verbose_name = u'채팅'


class DefaultMessages(models.Model):
    target = models.CharField(max_length=50, blank=True, default='', verbose_name=u'대상')
    message = models.TextField(default='', verbose_name=u'메세지')

    user = models.ForeignKey(User, null=True, verbose_name=u'보낸 사람', limit_choices_to={'is_staff': True})

    created_at = models.DateTimeField(verbose_name=u'생성일(순서)')

    def __unicode__(self):
        return u"[%s] - %s" % (self.user_id, self.message)

    class Meta:
        verbose_name_plural = u'기본 메세지 목록'
        verbose_name = u'기본 메세지'


class Article(models.Model):
    CATEGORIES = (
        ('location', u'위치'),
        ('notice', u'공지'),
        ('calendar', u'일정'),
        ('', u'일반'),
    )

    author = models.ForeignKey(User, db_index=True, verbose_name=u'작성자', on_delete=models.CASCADE,
                               limit_choices_to={'is_staff': True})

    category = models.CharField(max_length=20, blank=True, default='', choices=CATEGORIES, verbose_name=u'제목')
    title = models.CharField(max_length=50, default='', verbose_name=u'제목')
    content = models.TextField(default='', verbose_name=u'내용')

    is_notice = models.BooleanField(default=False, verbose_name=u'공지여부')
    is_secret = models.BooleanField(default=False, verbose_name=u'비밀글 여부')

    attach_image = models.ImageField(upload_to='article/', null=True, blank=True, verbose_name=u'첨부이미지')

    created_at = models.DateTimeField(auto_now_add=True, verbose_name=u'생성일')

    def __unicode__(self):
        return u"[%s] %s" % (self.category, self.title)

    class Meta:
        verbose_name_plural = u'글 목록'
        verbose_name = u'글'


class Gallery(models.Model):
    title = models.CharField(max_length=50, blank=True, default='', verbose_name=u'제목')
    description = models.TextField(default='', blank=True, verbose_name=u'설명')
    path = models.ImageField(upload_to='gallery/', verbose_name=u'이미지')

    def __unicode__(self):
        return u"[%s] %s" % (self.id, self.title)

    class Meta:
        verbose_name_plural = u'갤러리 목록'
        verbose_name = u'갤러리'

templates/article.html
{% extends "base.html" %}
{% load humanize %}
{% load staticfiles %}
{% load customtags %}
{% block body %}
	<div class="activity">
		<div class="header">
			<button class="btn btn-back">
				<i class="fa fa-angle-left"></i>
				{{ bride_groom.name }}
			</button>
			<button class="btn btn-list pull-right">
				<i class="fa fa-th-list"></i>
			</button>
		</div>
		<div class="content scroll-section">
			<div class="scroller">
				<section>
					<div class="title media">
						<div class="media-left">
							<div class="profile">
								<img src="{% static "assets/img/profile" %}/{{ article.author.profile }}">
							</div>
						</div>
						<div class="media-body">
							<div class="name">{{ article.author.name }}</div>
							<div class="date" title="{{ article.created_at|date:"Y-m-d" }}T{{ article.created_at|date:"H:i:s" }}+09:00">{{ article.created_at|date:"Y년 n월 j일 a g:i" }}</div>
						</div>
					</div>
					<article>
						{{ article.title }}<br/><br/>
						{{ article.content|safe|linebreaksbr }}
						{% if article.attach_image %}
							<img src="{{ MEDIA_URL }}{{ article.attach_image }}" class="attach_image">
						{% endif %}
					</article>
				</section>
			</div>
		</div>
	</div>
{% endblock %}
{% block javascript %}
<script src="{% static "libs/plugins/prettydate/jquery.prettydate.js" %}"></script>
<script src="{% static "libs/plugins/prettydate/jquery.prettydate-kr.js" %}"></script>
<script>
	var name = '';

	$(document).ready(function(){
		$('.date').prettyDate({
			interval: 1000
		});

		$('.btn-list').on('click', function(e){
			// 돌아가려는데 이전단계에서 부른게 board에서 부른 경우라면 back 으로 돌아간다.
			if (document.referrer.indexOf('board') != -1) {
				window.history.back();
			} else {
				location.replace("{% url "card:board" %}");
			}
		});
	});
</script>
<script type="text/jsx">
	// React Code Goes Here
</script>
{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="kr">
<head>
	<meta charset="utf-8">
{#	<meta http-equiv='X-UA-Compatible' id='X-UA-Compatible' content='IE=edge'/>#}
	<meta http-equiv="x-ua-compatible" content="ie=edge">
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
{#	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">#}
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, shrink-to-fit=no">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="mobile-web-app-capable" content="yes">

	<meta property="og:type" content="website">
    <meta property="og:image" content="http://20140848.me{% static "assets/img/site_thumbnail.png" %}">
	<meta property="og:title" content="Euiju Han ♥ Jungsuk Hyung Wedding Invitation">
	<meta property="og:url" content="http://20140848.me/card/">
	<meta property="og:description" content="한의주♥형정석의 모바일 청첩장 페이지입니다.">
	<meta property="og:locale" content="ko_KR">

	<title>Euiju Han ♥ Jungsuk Hyung Wedding Invitation</title>

	<!-- Bootstrap -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css" integrity="sha384-y3tfxAZXuh4HwSYylfB+J125MxIs6mR5FOHamPBG064zB+AFeWH94NdvaCBm8qnd" crossorigin="anonymous">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
{#	<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jquerymobile/1.4.5/jquery.mobile.min.css">#}
	<link rel="stylesheet" href="{% static "assets/css/app.css" %}?{% now "Ymdh" %}">
	{% block stylesheet %}{% endblock %}

	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
		<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>
<body>
	<div class="overlay"></div>
	<main>
	{% block body %}{% endblock %}
	</main>
	<div class="template" style="display: none;">
	{% block template %}{% endblock %}
	</div>
	<!-- jQuery first, then Bootstrap JS -->
	<script src="{% static "assets/js/vender/tether.min.js" %}"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/js/bootstrap.min.js" integrity="sha384-vZ2WRJMwsjRMW/8U7i6PWi6AlO1L79snBrmgiDpgIWJ82z8eA5lenwvxbMV1PAh7" crossorigin="anonymous"></script>
	<script src="{% static "libs/js/wedding.js" %}?{% now "Ymdh" %}"></script>
{% block javascript %}{% endblock %}
</body>
</html>

templates/board.html
{% extends "base.html" %}
{% load humanize %}
{% load staticfiles %}
{% load customtags %}
{% block body %}
	<div class="activity">
		<div class="header">
			<button class="btn btn-back"{% comment %} href="{% url "card:chat" %}"{% endcomment %}>
				<i class="fa fa-angle-left"></i>
				{{ bride_groom.name }}
			</button>
		</div>
		<div class="content scroll-section">
			<div class="scroller">
				{% for article in articles %}
				<section href="{% url "card:article" %}?id={{ article.id }}">
					<div class="title media">
						<div class="media-left">
							<div class="profile">
								<img src="{% static "assets/img/profile" %}/{{ article.author.profile }}">
							</div>
						</div>
						<div class="media-body">
							<div class="name">{{ article.author.name }}</div>
							<div class="date" title="{{ article.created_at|date:"Y-m-d" }}T{{ article.created_at|date:"H:i:s" }}+09:00">{{ article.created_at|date:"Y년 n월 j일 a g:i" }}</div>
						</div>
					</div>
					<article>
						{{ article.title }}<br/><br/>
						{{ article.content|safe|linebreaksbr|truncatechars:255 }}
					</article>
				</section>
				{% endfor %}
			</div>
		</div>
	</div>
{% endblock %}
{% block javascript %}
<script src="{% static "libs/plugins/prettydate/jquery.prettydate.js" %}"></script>
<script src="{% static "libs/plugins/prettydate/jquery.prettydate-kr.js" %}"></script>
<script>
	var name = '';

	$(document).ready(function(){
		$('.date').prettyDate({
			interval: 1000,
			attribute: 'title'
		});
	});
</script>
<script type="text/jsx">
	// React Code Goes Here
</script>
{% endblock %}

templates/chatrooms.html
{% extends "base.html" %}
{% load humanize %}
{% load staticfiles %}
{% load customtags %}
{% block body %}
	<div class="activity">
		<div class="header">
			<button class="btn btn-back"{% comment %} href="{% url "card:chat" %}"{% endcomment %}>
				<i class="fa fa-angle-left"></i>
				{{ bride_groom.name }}
			</button>
		</div>
		<div class="content scroll-section">
			<div class="scroller">
				{% for chatroom in chatrooms %}
				<section href="{% url "card:chat" %}?id={{ chatroom.id }}">
					<div class="title media">
						<div class="media-left">
							<div class="profile">
								<img src="{% static "assets/img/profile/thm_general_default_profile_image.png" %}">
							</div>
						</div>
						<div class="media-body">
							<div class="date pull-right" style="margin-top: 0.4rem;" title="{{ chatroom.chatlogs_set.all.last.created_at|date:"Y-m-d" }}T{{ chatroom.chatlogs_set.all.last.created_at|date:"H:i:s" }}+09:00">
								{{ chatroom.chatlogs_set.all.last.created_at|date:"Y년 n월 j일 a g:i" }}
							</div>
							<div class="name">
{#								{% for name in chatroom.members_names %}{{ name }}{% if not forloop.last %},{% endif %}{% endfor %}#}
								{{ chatroom.owner.name }}_{{ chatroom.owner.last_number }}
							</div>
							<div class="message">
								{{ chatroom.chatlogs_set.all.last.message|truncatechars:100 }}
							</div>
						</div>
					</div>
				</section>
				{% endfor %}
			</div>
		</div>
	</div>
{% endblock %}
{% block javascript %}
<script src="{% static "libs/plugins/prettydate/jquery.prettydate.js" %}"></script>
<script src="{% static "libs/plugins/prettydate/jquery.prettydate-kr.js" %}"></script>
<script>
	var name = '';

	$(document).ready(function(){
		$('.date').prettyDate({
			interval: 1000,
			attribute: 'title'
		});
	});
</script>
<script type="text/jsx">
	// React Code Goes Here
</script>
{% endblock %}

templates/event.html
{% extends "base.html" %}
{% load staticfiles %}
{% block body %}
이벤트 페이지로 연결합니다.
{% endblock %}
{% block javascript %}
<script>
	$(document).ready(function(){
		location.href = 'https://open.kakao.com/o/s82FCnj';
	});
</script>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block body %}
	<!-- 스플래쉬 영역 -->
	<div class="splash-wrapper">
		<div class="timebox">
			<p>2016.04.30. SAT PM 3:00</p>
			<h1 id="countdown"></h1>
		</div>
		<div class="detail-wrapper">
			<button class="btn btn-primary btn-brd" id="show-detail">자세히보기 <i class="fa fa-angle-right"></i></button>
		</div>
	</div>
	<div class="intro-wrapper" style="display: none;">
		<div class="scroll-section">
			<div class="scroller">
				<div class="form-wrapper">
					<div class="profile-box">
						<h6 class="text-center">한의주♡형정석</h6>
						<img src="{% static "assets/img/profile/hej_hjs.png" %}">
					</div>
					<div class="help-block">
						이름과 휴대폰 전화번호 뒷 4자리를 입력해주세요.<br/>
						입력하신 정보는 개별 맞춤 청첩장을 제공하는데 사용됩니다.
					</div>
					<form class="form-horizontal" id="user-info" method="POST" action="{% url 'card:chat' %}">
						{% csrf_token %}
						<div class="form-group">
							<input type="text" id="name" name="name" class="form-control" placeholder="이름" required autocomplete="off">
						</div>
						<div class="form-group">
							<input type="text" id="last_number" name="last_number"class="form-control" placeholder="전화번호 뒷 4자리" required autocomplete="off">
						</div>
						<div class="form-group">
							<button type="submit" class="btn btn-block btn-primary">입장하기</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock %}
{% block javascript %}
<script src="{% static "libs/countdown/jquery.countdown.js" %}"></script>
<script src="{% static "libs/validate/jquery.validate.js" %}"></script>
<script>
	var name = '';

	$(document).ready(function(){

		$(window).on('resize', function(e){
			relocateTimeBox();
		});

		initSplash();
		relocateTimeBox();
	});

	function initSplash() {
		var ts = new Date(2016, 3, 30, 15, 00);

		// 유저정보를 가지고 있다면 미리 채워준다.
		var userinfo = getCookie('userinfo');
		if (userinfo) {
			var tmp = deserialize(userinfo);
			$('#name').val(tmp['name']);
			$('#last_number').val(tmp['last_number']);
		}

		$('#show-detail').on('click', function(e){
			// 최근 하루동안 방문한 적이 있으면 굳이 물어보지 않고 채팅창으로 이동
			if (getCookie('isVisit') && getCookie('userinfo')) {
				$('#user-info').trigger('submit');
			} else {
				// 최근 방문한 기록이 없다면 유저정보를 받은 후 기록 후 채팅창으로 이동
				showUserInfo();
			}
		});

		$('#countdown').countdown({
			timestamp	: ts,
			callback	: function(days, hours, minutes, seconds){

				var message = "";

				message += "D-" + days + " " + hours.zf(2) + ":" + minutes.zf(2) + ":" + seconds.zf(2);

				$('.timebox h1').html(message);
			}
		});

		$('input').on('focus', function(e){
			setTimeout(function(){
				$('.scroller').scrollTop($('.scroller')[0].scrollHeight);
			}, 100);
		});
	}

	function showUserInfo() {
		$('.splash-wrapper').fadeOut();
		$('.intro-wrapper').fadeIn();

		$('#user-info').validate({
			submitHandler: function(form) {
				// 방문기록 체크
				setCookie('isVisit', 1, 30);

				// 유저정보 기록
				setCookie('userinfo', $(form).serialize(), 30);

				location.href = '{% url "card:chat" %}';

				return false;
			},
			rules: {
				last_number: {
					number: true
				}
			},
			messages: {
				name: {
					required: "한글 이름을 입력해주세요."
				},
				last_number: {
					required: "휴대폰 전화번호 4자리를 입력해주세요.",
					number: "숫자만 입력가능합니다"
				}
			}
		});
	}

	function relocateTimeBox() {
		$('.timebox').css({'top': $(window).outerHeight() / 2 + $('.timebox').outerHeight() / 10});
	}

	function toggleFullScreen() {
		if (!document.fullscreenElement &&    // alternative standard method
				!document.mozFullScreenElement && !document.webkitFullscreenElement && !document.msFullscreenElement ) {  // current working methods
			if (document.documentElement.requestFullscreen) {
				document.documentElement.requestFullscreen();
			} else if (document.documentElement.msRequestFullscreen) {
				document.documentElement.msRequestFullscreen();
			} else if (document.documentElement.mozRequestFullScreen) {
				document.documentElement.mozRequestFullScreen();
			} else if (document.documentElement.webkitRequestFullscreen) {
				document.documentElement.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);
			}
		} else {
			if (document.exitFullscreen) {
				document.exitFullscreen();
			} else if (document.msExitFullscreen) {
				document.msExitFullscreen();
			} else if (document.mozCancelFullScreen) {
				document.mozCancelFullScreen();
			} else if (document.webkitExitFullscreen) {
				document.webkitExitFullscreen();
			}
		}
	}
</script>
<script type="text/jsx">
	// React Code Goes Here
</script>
{% endblock %}

templates/userinfo.html
{% extends "base.html" %}
{% load staticfiles %}
{% block body %}

{% endblock %}
{% block template %}
<div class="message-row" id="tmpl-message">
	<div class='profile'>
		<img src=''>
	</div>
	<div class='message-box'>
		<div class='name'></div>
		<div class='message'>
			<span class="text"></span>
			<div class='extra'>
				<div class='badge'></div>
				<div class='date'></div>
			</div>
		</div>
	</div>
</div>
{% endblock %}
{% block javascript %}
<script>
	var name = '';

	$(document).ready(function(){
		$('#test').on('click', function(e){
			toggleFullScreen();
		});

		resizeChatBox();
		resizeMenuBox();
		centeredText();

		$(window).on('resize', function(e){
			resizeTalkBox();
			resizeChatBox();
			resizeMenuBox();
			relocateTimeBox();
			centeredText();
		});

		initSideMenu();
		initInputBox();
		resizeTalkBox();

		initSplash();
		relocateTimeBox();
	});

	function showMessage(type, message) {
		var template = $('#tmpl-message').clone().removeAttr("id").addClass(type);
		var now = new Date().format("a/p hh:mm");

		var prev_message = $('.scroller .message-row').last();
		var prev_message_date = prev_message.find('.date');

		if (prev_message.hasClass(type) && prev_message_date.text() == now) {
			prev_message_date.text('');
		}

		if (name == '') {
			name = window.prompt('이름을 입력해주세요');
		}

		template.find('.profile img').attr('src', '{% static "assets/img/profile/hej_hjs.png" %}');
		template.find('.name').text(name);
		template.find('.text').html(message.replace(/\n/g, "<br />"));
		template.find('.date').text(now);

		$('.talk-box .scroller').append(template);

	}

	function initSplash() {
		var ts = new Date(2016, 3, 30, 15, 00);
		$('#show-detail').on('click', function(e){
			$('.splash-wrapper').fadeOut();
		});

		$('#countdown').countdown({
			timestamp	: ts,
			callback	: function(days, hours, minutes, seconds){

				var message = "";

				message += "D-" + days + " " + hours.zf(2) + ":" + minutes.zf(2) + ":" + seconds.zf(2);

				$('.timebox h1').html(message);
			}
		});
	}

	function relocateTimeBox() {
		$('.timebox').css({'top': $(window).outerHeight() / 2 + $('.timebox').outerHeight() / 5});
	}

	function initInputBox() {

		$('textarea').on('keyup', function(e){

			var _text = $(this).val();

			this.style.height = "1px";
			this.style.height = this.scrollHeight+"px";

			resizeChatBox();
			resizeTalkBox();

			if (_text.length > 0) {
				$('.btn-send').removeAttr('disabled');
			} else {
				$('.btn-send').attr('disabled', 'disabled');
			}
		});

		$('textarea').on('keydown', function(e){
			if (e.keyCode == 13 && !e.shiftKey) {
				e.preventDefault();

				// 엔터받으면 전송하도록 한다.
				sendMessage();
			}
		});

		$('.btn-send').on('click', function(){
			sendMessage();
		});
	}

	function sendMessage() {
		var _textarea = $('textarea');
		var _scroller = $('.scroller');

		if (_textarea.val().startsWith('@')) {
			showMessage('other', _textarea.val());
		} else {
			showMessage('me', _textarea.val().replace('@', ''));
		}

		_textarea.val('');
		_textarea.trigger('keyup');

		_textarea.focus();

		// 맨 아래로 위치시키기
		_scroller.scrollTop(_scroller[0].scrollHeight);
	}

	function resizeMenuBox() {
		var width = $(window).width() - 80;
		var right = -(width + 40);

		$('.menu-wrapper').css({'width': width, 'right': right});
	}

	function initSideMenu() {
		$('.btn-menu').on('click', function(e){
			$('.menu-wrapper').addClass('active');
			$('.overlay').addClass('active');
		});

		$('.overlay').on('click', function(e) {
			$('.menu-wrapper').removeClass('active');
			$(this).removeClass('active');
		});
	}

	function centeredText() {
		var _name = $('.splash-wrapper .names');

		var _height = $(window).height();

		_name.css({'bottom': _height * 45 / 100});
	}

	function resizeChatBox(){
		var _textarea = $('.input-box textarea');
		var height = _textarea.outerHeight();
		var width = $(window).outerWidth();

		$('.input-box').height(height);
		$('.btn-plus').outerHeight(height);

		_textarea.outerWidth(width - 48);

		// 메세지 상자 최대 크기
		$('.message-box .message').css({'max-width': width - 20 - 47 - 85});
	}

	function resizeTalkBox(){
		var height = $(window).height();
		var input_height = $(".chat-wrapper .input-box").outerHeight();
		var title_height = $(".chat-wrapper .title").outerHeight();

		$('.scroller').height(height - title_height - input_height);
	}

	function toggleFullScreen() {
		if (!document.fullscreenElement &&    // alternative standard method
				!document.mozFullScreenElement && !document.webkitFullscreenElement && !document.msFullscreenElement ) {  // current working methods
			if (document.documentElement.requestFullscreen) {
				document.documentElement.requestFullscreen();
			} else if (document.documentElement.msRequestFullscreen) {
				document.documentElement.msRequestFullscreen();
			} else if (document.documentElement.mozRequestFullScreen) {
				document.documentElement.mozRequestFullScreen();
			} else if (document.documentElement.webkitRequestFullscreen) {
				document.documentElement.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);
			}
		} else {
			if (document.exitFullscreen) {
				document.exitFullscreen();
			} else if (document.msExitFullscreen) {
				document.msExitFullscreen();
			} else if (document.mozCancelFullScreen) {
				document.mozCancelFullScreen();
			} else if (document.webkitExitFullscreen) {
				document.webkitExitFullscreen();
			}
		}
	}
</script>
<script type="text/jsx">
	// React Code Goes Here
</script>
{% endblock %}